on:
  push:
  pull_request:

name: demo_container

jobs:
  demo_container:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        singularity_version:
          - '3.7.4'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Download container
        run: singularity pull library://richelbilderbeek/default/plinkr:v0.15.1

      - name: Show container help
        run: singularity run-help plinkr_v0.15.1.sif

      - name: Show container script
        run: singularity inspect --deffile plinkr_v0.15.1.sif

      - name: ls
        run: ls

      - name: Run container
        run: singularity exec plinkr_v0.15.1.sif Rscript demo_container.R

